spring.data.mongodb:
  database: starwars
  uri: mongodb://localhost:27017

integration:
  headers:
     name: user-agent
     value: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
  swapi: 
    planets: 
      https://swapi.co/api/planets/
    
swagger:
  basePackege: br.com.api.controllers
  pathSelectorsRegex: /.*
  title: Doc API
  description: Documentação API Star Wars
  version: 1.0.0